name: svitifouka
on:
  schedule:
    - cron: "05 4-16 * * *"
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: '1.21'
    - name: Run
      run: go run svitifouka.go
      env:
        ENTSOE_TOKEN: ${{ secrets.ENTSOE_TOKEN }}
        GOTWI_API_KEY: ${{ secrets.GOTWI_API_KEY }}
        GOTWI_API_KEY_SECRET: ${{ secrets.GOTWI_API_KEY_SECRET }}
        GOTWI_ACCESS_TOKEN: ${{ secrets.GOTWI_ACCESS_TOKEN }}
        GOTWI_ACCESS_TOKEN_SECRET: ${{ secrets.GOTWI_ACCESS_TOKEN_SECRET }}
